Project: data-playground
CiCdEnvironment:
    AccountId: '952284683965'
    Region: eu-west-1
    GitHubRepo: 'codiply/aws-data-analytics-playground'
    GitBranch: 'main'
    GitHubOauthTokenSsmParameter: '/github/oauth-token'
Environments:
  Dev:
    Enabled: true
    Name: Development
    ShortName: Dev
    AccountId: '952284683965'
    Region: eu-west-1
    NeedsManualApproval: false
    ConfigOverrides: ~
  Pre:
    Enabled: false
    Name: Preproduction
    ShortName: Pre
    AccountId: '847334008802'
    Region: eu-west-1
    NeedsManualApproval: false
    ConfigOverrides: ~
  Pro:
    Enabled: false
    Name: Production
    ShortName: Pro
    AccountId: '814312087360'
    Region: eu-west-1
    NeedsManualApproval: true
    ConfigOverrides: ~
GlobalConfig:
  StackSwitches:
    Base: true
    Common: false
    DataWarehouse: false
    Etl: false
    RelationalDatabase: false
    Testing: false
    TweetsToS3: false
  Common:
    XRayEnabled: false
    TrustedIpRangeSsmParameter: '/data-analytics-playground/trusted-ip-range'
    KeyName: 'dev.codiply.panos.ireland'
  EcsCluster:
    ContainerInsightsEnabled: true
  Etl:
    Crawlers:
      TweetsRawData:
        ScheduleCronExpression: '00 * * * ? *'
  EventFirehose:
    BufferingIntervalSeconds: 60
    BufferingSizeMiB: 5
    DataOutputExpirationDays: 30
    ErrorOutputExpirationDays: 30
  Redshift:
    MasterUsername: 'admin'
    MasterPasswordSsmParameter: '/data-analytics-playground/redshift/master-password'
    DefaultDatabaseName: 'playground_db'
    IsSingleNode: true
    NumberOfNodes: 2
  RelationalDatabase:
    InitialDatabaseName: 'playground_db'
    MasterUsername: 'postgres'
    MasterPasswordSsmParameter: '/data-analytics-playground/relational-database/master-password'
    MultiAz: false
  S3Bucket:
    ExpirationDays: 3
  TestInstance: ~
  Tweets:
    S3PathPrefix: 'tweets'
  TweetsFirehoseProducer:
    Enabled: true
    Filter: '#aws'
    MemoryLimitMiB: 512
    Cpu: 256
  TwitterApi:
    ConsumerKeySsmParameter: '/twitter-api/consumer-key'
    ConsumerSecretSsmParameter: '/twitter-api/consumer-secret'
    AccessTokenSsmParameter: '/twitter-api/access-token'
    AccessTokenSecretSsmParameter: '/twitter-api/access-token-secret'
  Vpc:
    CidrRange: '10.81.0.0/16'
    MaxAzs: 2
    NatGateways: 1
    UseNatInstances: true
    NatInstanceType: 't3.micro'