Project: data-playground
CiCdEnvironment:
    AccountId: '952284683965'
    Region: eu-west-1
Environments:
  Dev:
    Enabled: true
    Name: Development
    ShortName: Dev
    AccountId: '952284683965'
    Region: eu-west-1
    ConfigOverrides: ~
  Pre:
    Enabled: false
    Name: Preproduction
    ShortName: Pre
    AccountId: '847334008802'
    Region: eu-west-1
    ConfigOverrides: ~
  Pro:
    Enabled: false
    Name: Production
    ShortName: Pro
    AccountId: '814312087360'
    Region: eu-west-1
    ConfigOverrides: ~
GlobalConfig:
  S3Bucket:
    ExpirationDays: 3